### ISSUE TITLE
Failed deleting tweeted images

### ISSUE THREAD

**Issue by djaekim** [q-flux/SOEN341#113]
**Describe the bug**
Deleting a tweeted image does not get deleted in photo page

**To Reproduce**
1. Click tweet image
2. Find image to tweet
3. Click upload
4. Delete image
5. Go to photo page

**Expected behavior**
- image tweet should be deleted from database, and not shown on photo page

**Screenshots**
Deleted image still shown
![image](https://user-images.githubusercontent.com/26092570/54886735-b8290100-4e61-11e9-900a-0c274ca3da1d.png)

**Comment by kasrarad** [comment]
The code is correct.
Go to public folder->storage and delete the photo folder and run:
php artisan migrate:fresh

**Comment by djaekim** [comment]
It does work now. Not sure why it wasn't working before! Closing this issue now!
