### ISSUE TITLE
As a user I want to be able to login to my account. #6 [2]

### ISSUE THREAD

**Issue by djaekim** [q-flux/SOEN341#35]
**Describe the user story that is important for the core functionality of the twitter app**

**Describe what tasks that are involved in this user story**
A breakdown of the user story into individual tasks in bullet points. For each task you can put a reference to another issue for the tasks

**Additional context**
Add any other context or screenshots about the discussion regarding user story

**Comment by djaekim** [comment]
This is a sub user story from #6

**Comment by djaekim** [comment]
Implementation Tasks:
[1] Need a front end for login
[2] Need to search for username and password in the Database

**Comment by sourabh-rb** [comment]
Closing sub-user story as tasks #45 and #46 have been implemented and tested.
