### ISSUE TITLE
As a user, I need a text area where I can write my tweet. #6 [3]

### ISSUE THREAD

**Issue by sourabh-rb** [q-flux/SOEN341#37]
**Describe the user story that is important for the core functionality of the twitter app**

**Describe what tasks that are involved in this user story**
A breakdown of the user story into individual tasks in bullet points. For each task you can put a reference to another issue for the tasks

**Additional context**
Add any other context or screenshots about the discussion regarding user story

**Comment by djaekim** [comment]
This has been implemented, tested and merged. Closing this issue now.
