### ISSUE TITLE
As a user, I want to be able to register for an account. #6 [1]

### ISSUE THREAD

**Issue by djaekim** [q-flux/SOEN341#5]
User Story: 

User should be able to create a new account by registering, and login to their new account.

**Comment by djaekim** [comment]
This is sub-user story from #6

**Comment by djaekim** [comment]
Implementation Tasks:
[1] Need a front end for register 
[2] Require data base structure for user 
[3] Need to validate register information 
[4] Need to save user information to DB

**Comment by sourabh-rb** [comment]
Closing the sub-user story as implementation tasks #41, #42, #43, and #44 have been implemented and tested.
