### ISSUE TITLE
As a user I want to be able register and login for an account so that I can start posting tweets

### ISSUE THREAD

**Issue by djaekim** [q-flux/SOEN341#6]
User Story:

From the text box field in their account page, user should be able to post a new tweet

**Comment by sourabh-rb** [comment]
@Saicharanduduka  from a front end perspective

- need a text box to take user input

- limit the user input to 140 characters

- button for the user to post and confirm his tweet.

**Comment by Saicharanduduka** [comment]
@sourabh-rb yeah its looking good but we can use some templates to make our work easier and what about back end implementation.

**Comment by sourabh-rb** [comment]
yup! we can look into some templates for the front end! 
We'll be using laravel, so we can create tables and add controllers using the framework to handle the back end stuff.

**Comment by Saicharanduduka** [comment]
Ok sourab thanks, will go ahead and start implementing this .

**Comment by djaekim** [comment]
SubUserStories:
[1]  As a user I want to be able to register for an account
[2] As a user I want to be able to login to my account
[3] As a user I want to post a tweet

**Comment by djaekim** [comment]
All tasks have been implemented for this user story. Closing this issue now.

**Comment by djaekim** [comment]
![image](https://user-images.githubusercontent.com/26092570/53846146-dd6cd280-3f79-11e9-936d-869559223b89.png)
