### ISSUE TITLE
As a user, I can follow a user

### ISSUE THREAD

**Issue by samuelbeaubien** [q-flux/SOEN341#62]
Definition (criteria) of done:
- There is a button on the user pages that allow you to follow a user
- User can see the list of people who follow them
- User can see the list of people they follow

Tasks:
- Add a button on user page that allows you to follow that user (Jake)
     - Input: Click event
     - Output: Request
- Create controller that updates database with new follower relationship (Jake)
     - Input: ID of follower, ID of followed 
     - Output: Updates the database
-  Update home controller and home view to see of your followers on home page (Jake)
     - Input: Home route
     - Output: Home view
-  Update home controller and home view to see people who follow you on home page (Jake)
     - Input: Home route
     - Output: Home view

Notes:
- DB structure for following a user
- ![image](https://user-images.githubusercontent.com/26092570/53253978-6fc6c980-3690-11e9-8c79-6378e2e4d05f.png)

**Comment by samuelbeaubien** [comment]
This has been implemented, tested and merged. Closing this issue now.

**Comment by djaekim** [comment]
ACCEPTANCE TESTS

![image](https://user-images.githubusercontent.com/26092570/54492993-acf23600-48a1-11e9-8b2b-4c0eec3bf807.png)
