### ISSUE TITLE
As a user, I want to like posts

### ISSUE THREAD

**Issue by samuelbeaubien** [q-flux/SOEN341#64]
Definition of done:
- I want to llike any posts, but only once

Task
- Create table in database for likes (Kasra)
![image](https://user-images.githubusercontent.com/26092570/53257222-9dfbd780-3697-11e9-9150-f7302dd8d5f2.png)

- Create method that gets the number of like for a given tweet (Kasra)
     - Input: Tweet ID
     - Output: Number of likes
- Create a method that checks whether a user can like a tweet (Vinita)
     - Input: User ID, Tweet ID
     - Output: True/false
- Modify all controllers that need to know the number of likes in a tweet (Kasra)
     

Note:
- Create like table with postID, and userID

**Comment by samuelbeaubien** [comment]
This has been implemented, tested and merged. Closing this issue now.

**Comment by djaekim** [comment]
ACCEPTANCE TESTS 

![image](https://user-images.githubusercontent.com/26092570/54492959-6b618b00-48a1-11e9-96e8-a674cc33fdc7.png)
