### ISSUE TITLE
Create class diagram of project

### ISSUE THREAD

**Issue by samuelbeaubien** [q-flux/SOEN341#66]
Definition of done
- We have a class diagram of all components in the projects

Tasks
- Do class diagram

**Comment by samuelbeaubien** [comment]
This has been implemented, tested and merged. Closing this issue now.

**Comment by sourabh-rb** [comment]
![flux_arch_diagram](https://user-images.githubusercontent.com/40620479/55995040-6ebe1b80-5c81-11e9-8e08-f23b21ee64ce.png)

**Comment by sourabh-rb** [comment]
![model](https://user-images.githubusercontent.com/40620479/55995061-809fbe80-5c81-11e9-8bc9-6708a0af5d3d.jpg)


![views](https://user-images.githubusercontent.com/40620479/55995065-839aaf00-5c81-11e9-8a1b-ec7856ed8c46.jpg)


![Controllers](https://user-images.githubusercontent.com/40620479/55995069-86959f80-5c81-11e9-8c7a-9d4e6eafdb13.jpg)
![full_proj](https://user-images.githubusercontent.com/40620479/55995073-89909000-5c81-11e9-81bd-1091db26755a.jpg)
![test](https://user-images.githubusercontent.com/40620479/55995077-8d241700-5c81-11e9-8a25-2e26f334a0fa.jpg)

**Comment by djaekim** [comment]
<h1> MODEL</h1>

![model](https://user-images.githubusercontent.com/40620479/55995061-809fbe80-5c81-11e9-8bc9-6708a0af5d3d.jpg)

**Comment by djaekim** [comment]
<h1> VIEW</h1>

![views](https://user-images.githubusercontent.com/40620479/55995065-839aaf00-5c81-11e9-8a1b-ec7856ed8c46.jpg)

**Comment by djaekim** [comment]
<h1> CONTROLLER </h1>

![Controllers](https://user-images.githubusercontent.com/40620479/55995069-86959f80-5c81-11e9-8c7a-9d4e6eafdb13.jpg)

**Comment by djaekim** [comment]
<h1> TESTING FRAMEWORK </h1>

![test](https://user-images.githubusercontent.com/40620479/55995077-8d241700-5c81-11e9-8a25-2e26f334a0fa.jpg)

**Comment by sourabh-rb** [comment]
**Database Design**
![db_design](https://user-images.githubusercontent.com/40620479/56095490-9ee90280-5eab-11e9-989b-2214fcb5c0ee.PNG)
