### ISSUE TITLE
As a user, I want to be able to like another's tweet

### ISSUE THREAD

**Issue by djaekim** [q-flux/SOEN341#7]
User story:

From the list of other tweets posted by other users, the current user should be able to like a tweet.

**Comment by vinita1319** [comment]
Assessed at the beginning of SPRINT2 (meeting minutes)

Sub-user stories:
[1] Need to have like button at front end #47 
[2] Require a data base structure to store the Like flag in the table #48 

Story Points:
3

Priority:
MEDIUM

Risk:
MEDIUM

**Comment by djaekim** [comment]
All the sub user story and their tasks have been implemented and tested. Closing this issue now.
