### ISSUE TITLE
As a user, I want to edit my profile

### ISSUE THREAD

**Issue by samuelbeaubien** [q-flux/SOEN341#79]
DESCRIPTION (definition of done): 
- On my profile, I can add a biography
- User can add and modify a picture
- See who follow us
- See who we follow
- Other informations
     - Birthday
     - Marital status

SUB-USER STORIES
[1]  As a user I want to be able to upload my profile picture [#82]
[2]  As a user I want to be add information about my profile [ #83]

Acceptance tests #94 
- Click on button "edit"
- Change all wanted info directly on div 
- Click save
- Info is updated

Priority
- HIGH

Story points (on 10)
- 6

Risks
- If badly implemented, can accidentally delete your own info

**Comment by djaekim** [comment]
All the sub user story and their tasks have been implemented and tested. Closing this issue now.
