### ISSUE TITLE
As a user I want to search, find and go to the profile of another user

### ISSUE THREAD

**Issue by djaekim** [q-flux/SOEN341#9]
DESCRIPTION (definition of done):
- I can type the name of a user on a search bar 
- List of all similar user names appear (should only be the username, not full name)
- I can select (click) a user name
- When clicking on a user, I go to his home page

SUB-USER STORIES
[1] As a user I want to be able to able to search [#80]
[2] As a user I want to be taken to another user's profile [#81]

ACCEPTANCE TEST #93 
- User write name of other user
- User sees the username appear
- User click on the username
- User is redirected to the profile of the other user

PRIORITY
- HIGH

STORY POINTS (on 10)
- 3

RISKS
- If badly implemented, can go to other profiles as profile owner

**Comment by djaekim** [comment]
<h1> Result From sprint 1 meeting </h1> 

<h3> Subtasks </h3>

* Create a front end search bar
* Backend implementation of search based on search keywords

**Comment by Derpsantos** [comment]
To break down the search engine I think we need:
Front end:
-Text box for user input
-Button to initiate search
Back end:
-Efficiently searchable data structure for storing user profiles
-Hashing function to associate with user names and profiles
 
Let me know if you think we need anything else.

**Comment by djaekim** [comment]
The features have been implemented, we just have to write unit tests and acceptance test

**Comment by djaekim** [comment]
All the sub user story and their tasks have been implemented and tested. Closing this issue now.
