### ISSUE TITLE
Front end to hold user info (tweets, following, followers, likes)

### ISSUE THREAD

**Issue by sourabh-rb** [q-flux/SOEN341#91]
This is from the user story #79 

Design front end to hold user information. 
- This needs to be done for both authorized profile and other user profile

Eg: 
![image](https://user-images.githubusercontent.com/26092570/54494108-525ed700-48ad-11e9-9926-89f8cb13aff6.png)

**Comment by djaekim** [comment]
This has been implemented, tested, merged. Closing now.
