### ISSUE TITLE
Acceptance Testing for searching for another's profile (additional feature)

### ISSUE THREAD

**Issue by djaekim** [q-flux/SOEN341#93]
The spread sheet below shows the acceptance test done for 3 core features:

- https://docs.google.com/spreadsheets/d/1_Zmr8ywJvpxWJ4U2ZiSZwpxo8tnlkuf5jCvCYTJ7ZFE/edit#gid=0

- Follow the similar format for the acceptance testing for searching for another's profile #9

**Comment by djaekim** [comment]
Hey Jake, 

TravisCI shows that the build has failed because your tests failed. Could you look into them again?

Also, the task was related to acceptance testing, but not unit testing

**Comment by Derpsantos** [comment]
I believe I fixed the issue

**Comment by djaekim** [comment]
you did the wrong task. And, the issue has not been fixed if you take a look at this!
![image](https://user-images.githubusercontent.com/26092570/54919590-92d6da00-4ed7-11e9-99d9-2e252e7ebdd6.png)

**Comment by Derpsantos** [comment]
![search_test](https://user-images.githubusercontent.com/38963819/54950077-dc92e500-4f16-11e9-81ac-a441a03eb2f9.png)
![search_test_2](https://user-images.githubusercontent.com/38963819/54950086-e0266c00-4f16-11e9-87dd-c441fe99d4da.png)
