### ISSUE TITLE
Acceptance Testing for editing my profile page (additional feature)

### ISSUE THREAD

**Issue by djaekim** [q-flux/SOEN341#94]
The spread sheet below shows the acceptance test done for 3 core features:

- https://docs.google.com/spreadsheets/d/1_Zmr8ywJvpxWJ4U2ZiSZwpxo8tnlkuf5jCvCYTJ7ZFE/edit#gid=0

- Follow the similar format for the acceptance testing for editing another's profile #79

**Comment by Derpsantos** [comment]
![profile_edit_test](https://user-images.githubusercontent.com/38963819/54950144-fb917700-4f16-11e9-9364-57c33054a0d5.png)
